<?php namespace JF;
/**

Copyright 2018 JQueryForm.com
License: http://www.jqueryform.com/license.php

FormID:  jqueryform-74959a
Date:    2018-05-27 01:12:17
Version: v2.1.3
Generated by http://www.jqueryform.com

PHP 5.3+ is required.
If mailgun is used AND the form has file upload field, PHP 5.5+ is required.

*/

class Config {
	private static $config;

    public static function getConfig( $decode = true ){
    	self::$config = self::_getConfig( $decode );
    	self::overwriteConfig();
    	return self::$config;
    }

    private static function _getConfig( $decode = true ){
        ob_start();
        // ---------------------------------------------------------------------
        // JSON format config
        // Note: please make a copy before you edit config manually
        // ---------------------------------------------------------------------

/**JSON_START**/ ?>
{
    "formId": "jqueryform-74959a",
    "email": {
        "to": "",
        "cc": "",
        "bcc": "",
        "subject": "An Event was Reported on {Date} at {Time}",
        "template": ""
    },
    "admin": {
        "users": "admin:a73c1",
        "dataDelivery": "emailAndFile"
    },
    "thankyou": {
        "url": "",
        "message": "",
        "seconds": "10"
    },
    "autoResponse": {
        "includeAttachments": true,
        "subject": "",
        "template": ""
    },
    "seo": {
        "trackerId": "",
        "title": "",
        "description": "",
        "keywords": "",
        "author": ""
    },
    "mailer": "local",
    "smtp": {
        "host": "",
        "user": "",
        "password": ""
    },
    "mailgun": {
        "domain": "",
        "apiKey": "",
        "fromEmail": "",
        "fromName": ""
    },
    "styles": {
        "iCheck": {
            "enabled": true,
            "skin": "flat",
            "colorScheme": "black"
        },
        "Select2": {
            "enabled": true
        }
    },
    "logics": [
        {
            "disabled": false,
            "action": "show",
            "selector": "f8",
            "match": "all",
            "rules": [
                {
                    "disabled": false,
                    "selector": "f4",
                    "condition": "==",
                    "value": "Incident"
                }
            ]
        },
        {
            "disabled": false,
            "action": "hide",
            "selector": "f8",
            "match": "all",
            "rules": [
                {
                    "disabled": false,
                    "selector": "f4",
                    "condition": "!=",
                    "value": "Incident"
                }
            ]
        },
        {
            "disabled": false,
            "action": "show",
            "selector": "f9",
            "match": "any",
            "rules": [
                {
                    "disabled": false,
                    "selector": "f4",
                    "condition": "==",
                    "value": "Incident"
                },
                {
                    "disabled": false,
                    "selector": "f4",
                    "condition": "==",
                    "value": "Accident"
                }
            ]
        },
        {
            "disabled": false,
            "action": "hide",
            "selector": "f9",
            "match": "all",
            "rules": [
                {
                    "disabled": false,
                    "selector": "f4",
                    "condition": "==",
                    "value": "Behaviour"
                }
            ]
        },
        {
            "disabled": false,
            "action": "show",
            "selector": "f10",
            "match": "any",
            "rules": [
                {
                    "disabled": false,
                    "selector": "f4",
                    "condition": "==",
                    "value": "Incident"
                }
            ]
        },
        {
            "disabled": false,
            "action": "hide",
            "selector": "f10",
            "match": "any",
            "rules": [
                {
                    "disabled": false,
                    "selector": "f4",
                    "condition": "!=",
                    "value": "Incident"
                }
            ]
        },
        {
            "disabled": false,
            "action": "disable",
            "selector": "f8",
            "match": "all",
            "rules": [
                {
                    "disabled": false,
                    "selector": "f4",
                    "condition": "!=",
                    "value": "Incident"
                }
            ]
        },
        {
            "disabled": false,
            "action": "enable",
            "selector": "f8",
            "match": "any",
            "rules": [
                {
                    "disabled": false,
                    "selector": "f4",
                    "condition": "==",
                    "value": "Incident"
                }
            ]
        },
        {
            "disabled": false,
            "action": "show",
            "selector": "f13",
            "match": "all",
            "rules": [
                {
                    "disabled": false,
                    "selector": "f8",
                    "condition": "==",
                    "value": "Assault, Abuse or Neglect"
                }
            ]
        },
        {
            "disabled": false,
            "action": "hide",
            "selector": "f13",
            "match": "all",
            "rules": [
                {
                    "disabled": false,
                    "selector": "f8",
                    "condition": "!=",
                    "value": "Assault, Abuse or Neglect"
                }
            ]
        },
        {
            "disabled": false,
            "action": "disable",
            "selector": "f13",
            "match": "all",
            "rules": [
                {
                    "disabled": false,
                    "selector": "f8",
                    "condition": "!=",
                    "value": "Appears to be in discomfort\/Ill"
                }
            ]
        },
        {
            "disabled": false,
            "action": "enable",
            "selector": "f13",
            "match": "all",
            "rules": [
                {
                    "disabled": false,
                    "selector": "f8",
                    "condition": "==",
                    "value": "Assault, Abuse or Neglect"
                }
            ]
        }
    ],
    "fields": [
        {
            "label": "What is the nature of the event?",
            "field_type": "radio",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "Incident",
                        "checked": false,
                        "value": "Incident"
                    },
                    {
                        "label": "Accident",
                        "checked": false,
                        "value": "Accident"
                    },
                    {
                        "label": "Behaviour",
                        "checked": false,
                        "value": "Behaviour"
                    }
                ],
                "presetJson": "",
                "validators": {
                    "required": {
                        "enabled": true
                    }
                },
                "style": {
                    "columns": "col-3"
                }
            },
            "id": "f4",
            "cid": "c25"
        },
        {
            "label": "Where did the Event Happen?",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "Community-Indoors",
                        "checked": true,
                        "value": "Community-Indoors"
                    },
                    {
                        "label": "Community-Outdoors",
                        "checked": true,
                        "value": "Community-Outdoors"
                    },
                    {
                        "label": "House-Indoors",
                        "checked": true,
                        "value": "House-Indoors"
                    },
                    {
                        "label": "House-Outdoors",
                        "value": "House-Outdoors",
                        "checked": true
                    },
                    {
                        "label": "In Vehicle-Parked",
                        "value": "In Vehicle-Parked",
                        "checked": true
                    },
                    {
                        "label": "In Vehicle-Travelling",
                        "value": "In Vehicle-Travelling",
                        "checked": true
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    },
                    "required": {
                        "enabled": true
                    }
                },
                "presetJson": "",
                "multiple": false
            },
            "id": "f5",
            "cid": "c31"
        },
        {
            "label": "Who was involved?",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "Person",
                        "checked": true,
                        "value": "Person"
                    },
                    {
                        "label": "Person\/Person",
                        "checked": true,
                        "value": "Person\/Person"
                    },
                    {
                        "label": "Person\/Staff",
                        "checked": true,
                        "value": "Person\/Staff"
                    },
                    {
                        "label": "Person\/Person\/Staff",
                        "value": "Person\/Person\/Staff",
                        "checked": true
                    },
                    {
                        "label": "Person\/Public",
                        "value": "Person\/Public",
                        "checked": true
                    },
                    {
                        "label": "Family",
                        "value": "Family",
                        "checked": true
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    },
                    "required": {
                        "enabled": true
                    }
                },
                "presetJson": "",
                "multiple": false
            },
            "id": "f6",
            "cid": "c23"
        },
        {
            "label": "Event Cause",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "Appears to be in discomfort\/Ill",
                        "value": "Appears to be in discomfort\/Ill",
                        "checked": true
                    },
                    {
                        "label": "Asked to do something",
                        "checked": true,
                        "value": "Asked to do something"
                    },
                    {
                        "label": "Alone\/Not engaged in material or activities",
                        "checked": true,
                        "value": "Alone\/Not engaged in material or activities"
                    },
                    {
                        "label": "Could not get desired item\/activity",
                        "checked": true,
                        "value": "Could not get desired item\/activity"
                    },
                    {
                        "label": "Asked to wait",
                        "value": "Asked to wait",
                        "checked": true
                    },
                    {
                        "label": "Preferred item or activity removed or stopped",
                        "value": "Preferred item or activity removed or stopped",
                        "checked": true
                    },
                    {
                        "label": "Loud\/Disruptive environment",
                        "value": "Loud\/Disruptive environment",
                        "checked": true
                    },
                    {
                        "label": "Ongoing behaviour interrupted",
                        "value": "Ongoing behaviour interrupted",
                        "checked": true
                    },
                    {
                        "label": "Other person provoked",
                        "value": "Other person provoked",
                        "checked": true
                    },
                    {
                        "label": "Transitional time",
                        "value": "Transitional time",
                        "checked": true
                    },
                    {
                        "label": "Attention from others",
                        "value": "Attention from others",
                        "checked": true
                    },
                    {
                        "label": "Attention given to others",
                        "value": "Attention given to others",
                        "checked": true
                    },
                    {
                        "label": "Routine Task",
                        "value": "Routine Task",
                        "checked": true
                    },
                    {
                        "label": "New\/difficult task\/activity",
                        "value": "New\/difficult task\/activity",
                        "checked": true
                    },
                    {
                        "label": "Change of Routine",
                        "value": "Change of Routine",
                        "checked": true
                    },
                    {
                        "label": "Recent medication change",
                        "value": "Recent medication change",
                        "checked": true
                    },
                    {
                        "label": "Seemed unsettled or agitated",
                        "value": "Seemed unsettled or agitated",
                        "checked": true
                    },
                    {
                        "label": "Other",
                        "value": "Other",
                        "checked": true
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    },
                    "required": {
                        "enabled": true
                    }
                },
                "presetJson": "",
                "multiple": false
            },
            "id": "f7",
            "cid": "c25"
        },
        {
            "label": "What Happened?",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "Assault, Abuse or Neglect",
                        "value": "Assault, Abuse or Neglect",
                        "checked": true
                    },
                    {
                        "label": "Death(unexpected)",
                        "checked": true,
                        "value": "Death(unexpected)"
                    },
                    {
                        "label": "Financial",
                        "checked": true,
                        "value": "Financial"
                    },
                    {
                        "label": "Injury as a result of someone's behaviour",
                        "checked": true,
                        "value": "Injury as a result of someone's behaviour"
                    },
                    {
                        "label": "Major event involving multiple community agencies or Spectrum Care departments",
                        "value": "Major event involving multiple community agencies or Spectrum Care departments",
                        "checked": true
                    },
                    {
                        "label": "Major Systems Failure",
                        "value": "Major Systems Failure",
                        "checked": true
                    },
                    {
                        "label": "Medical",
                        "value": "Medical",
                        "checked": true
                    },
                    {
                        "label": "Medication",
                        "value": "Medication",
                        "checked": true
                    },
                    {
                        "label": "Near Miss",
                        "value": "Near Miss",
                        "checked": true
                    },
                    {
                        "label": "Property Damage",
                        "value": "Property Damage",
                        "checked": true
                    },
                    {
                        "label": "Tools\/Appliances",
                        "value": "Tools\/Appliances",
                        "checked": true
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    },
                    "required": {
                        "enabled": false
                    }
                },
                "presetJson": "",
                "multiple": false
            },
            "id": "f8",
            "cid": "c31"
        },
        {
            "label": "Treatment",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "Nil Treatment",
                        "value": "Nil Treatment",
                        "checked": true
                    },
                    {
                        "label": "Counselled\/Reassured",
                        "checked": true,
                        "value": "Counselled\/Reassured"
                    },
                    {
                        "label": "First Aid given at home",
                        "checked": true,
                        "value": "First Aid given at home"
                    },
                    {
                        "label": "G.P.",
                        "checked": true,
                        "value": "G.P."
                    },
                    {
                        "label": "Dentist",
                        "value": "Dentist",
                        "checked": true
                    },
                    {
                        "label": "Phone Ambulance",
                        "value": "Phone Ambulance",
                        "checked": true
                    },
                    {
                        "label": "A and E",
                        "value": "A and E",
                        "checked": true
                    },
                    {
                        "label": "Hospitalisation",
                        "value": "Hospitalisation",
                        "checked": true
                    },
                    {
                        "label": "PRN",
                        "value": "PRN",
                        "checked": true
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    }
                },
                "presetJson": "",
                "multiple": false
            },
            "id": "f9",
            "cid": "c49"
        },
        {
            "label": "Major System",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "Fire(House\/Centre evacuated and not usable)",
                        "checked": true,
                        "value": "Fire(House\/Centre evacuated and not usable)"
                    },
                    {
                        "label": "Natural Disaster(House\/Centre evacuated and not usable)",
                        "checked": true,
                        "value": "Natural Disaster(House\/Centre evacuated and not usable)"
                    },
                    {
                        "label": "Substantial damage to property(House\/Centre evacuated and not usable)",
                        "checked": true,
                        "value": "Substantial damage to property(House\/Centre evacuated and not usable)"
                    },
                    {
                        "label": "Major utilities supply disruption to House\/Centre\/Region(House\/Centre evacuated and not usable)",
                        "value": "Major utilities supply disruption to House\/Centre\/Region(House\/Centre evacuated and not usable)",
                        "checked": true
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    }
                },
                "presetJson": "",
                "multiple": false
            },
            "id": "f10",
            "cid": "c67"
        },
        {
            "label": "What Happened (Behaviour)",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "- Select -",
                        "value": "#novalue",
                        "checked": false
                    },
                    {
                        "label": "Option 1",
                        "checked": false
                    },
                    {
                        "label": "Option 2",
                        "checked": false
                    },
                    {
                        "label": "Option 3",
                        "checked": false
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    }
                },
                "presetJson": "",
                "multiple": false
            },
            "id": "f11",
            "cid": "c87"
        },
        {
            "label": "Was there any injury?",
            "field_type": "radio",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "Yes",
                        "checked": true,
                        "value": "Yes"
                    },
                    {
                        "label": "No",
                        "checked": true,
                        "value": "No"
                    }
                ],
                "presetJson": "",
                "style": {
                    "columns": "col-2"
                }
            },
            "id": "f13",
            "cid": "c109"
        },
        {
            "label": "Amount Involved",
            "field_type": "radio",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "Less than $20",
                        "checked": true
                    },
                    {
                        "label": "More than $20",
                        "checked": true
                    }
                ],
                "presetJson": "",
                "style": {
                    "columns": "col-2"
                }
            },
            "id": "f14",
            "cid": "c135"
        },
        {
            "label": "Submit Button",
            "field_type": "submit",
            "required": true,
            "field_options": {
                "page": {
                    "title": "Submit",
                    "labelPrev": "< Back",
                    "showPageNumnber": false,
                    "pageNumberText": "{page} \/ {total}"
                },
                "images": {
                    "urls": "",
                    "slideshow": false
                }
            },
            "labelHide": true,
            "submit": {
                "label": "",
                "icon": "",
                "checkRequiredFields": ""
            },
            "id": "f0",
            "cid": "c0"
        }
    ],
    "gdpr": {
        "consentFieldId": "",
        "saveData": "no"
    },
    "licenseKey": ""
}
<?php /**JSON_END**/

        $json = ob_get_clean() ;

        return $decode ? json_decode( trim($json), true ) : $json;
    } // end of getConfig()

    private static function getValue( $fieldId, $default = NULL ){
        return isset( $_POST[$fieldId] ) ? $_POST[$fieldId] : $default ;
    }

    private static function overwriteConfig(){
    	//self::get_to();
    }

    private static function get_to(){
    	$value = self::getValue( 'c25' );
    	$to = array(
    		'Option 1' => 'a@a.com',
    		'Option 2' => 'b@b.com',
    		'Option 3' => 'c@c.com',
    	);

    	if( isset( $to[$value] ) ){
    		self::$config['email']['to'] = $to[ $value ];
    	};
    }

} // end of Config class
